AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'
    - 'scripts/**/*'
    - 'db/**/*'
Rails:
  Enabled: true
Style/GuardClause:
  MinBodyLength: 1
Style/AndOr:
  EnforcedStyle: conditionals
Style/PercentLiteralDelimiters:
  PreferredDelimiters: {}
Style/Alias:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Max: 150
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Rails/ActionFilter:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Style/Lambda:
  EnforcedStyle: 'literal'
Style/NilComparison:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/BlockLength:
  # RSpec nervt
  ExcludedMethods: ['task', 'namespace', 'get', 'post', 'describe', 'context', 'specify', 'it', 'route_param']
Bundler/OrderedGems:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false



