language: ruby

addons:
  postgresql: 9.3

rvm:
  - 2.2

services: [ redis ]

branches:
  only:
    - master

before_script:
  - cp config/secrets.yml.example config/secrets.yml
  - psql -c 'create database hrfilter_test' -U postgres
  - cp config/application.hrfilter.yml config/application.yml
  - "bundle exec rake db:schema:load RAILS_ENV=test"

script:
  - bundle exec rspec

bundler_args: "--without development production"
