default: &default
  site_name: 'HRfilter.de'
  short_name: 'HRfilter'
  from: 'noreply@hrfilter.de'
  key: 'hrfilter'
  database: hrfilter_<%= Rails.env.sub('elopment','') %>
  email: 'info@example.com'
  google_site_verification: ""
  host: 'localhost:3000'
  max_age: 14
  person: Stefan Wienert
  intro: |
    HRfilter.de ist ein Aggregator für Nachrichten aus dem Personalwesen / HR-Bereich. Zusammengefasst werden News aus <a href='/quellen'>bekannten deutsch- und englischsprachigen Blogs und Newsquellen</a> &ndash; Gebündelt und sortiert nach Relevanz und Beliebtheit in Social Media.
  explanation: |
    Ein Aggregator für News rund um das Thema Personal + HR. Dabei werden die News nach Aktualität und Viralität bewertet und sortiert. Außerdem wird eine Klassifizierung vorgenommen.
  credits: |
    Dies ist ein privates Projekt von <a href='http://www.stefanwienert.de'>mir</a>. Ich habe das Projekt ins Leben gerufen, um mich, als fachfremder Softwareentwickler, effektiv und schnell über alle News aus dem Fachbereich auf dem Laufenden zu halten.
  tracking_code: |
    <script type="text/javascript">
    </script>


development:
  << : *default

test:
  << : *default

production:
  << : *default


