development:
  adapter: postgresql
  encoding: unicode
  database: <%= ::Configuration.database %>
  template: template0
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ::Configuration.database %>
  template: template0
  pool: 5

