development:
  adapter: postgresql
  encoding: unicode
  database: hrcollect_dev
  template: template0
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: hrcollect_test
  template: template0
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: hrcollect
  template: template0
  pool: 5

