development:
  adapter: postgresql
  encoding: unicode
  database: hrfilter_<%= ENV['USER'] %>_dev
  template: template0
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: "hrfilter_test"
  template: template0
  pool: 5

production:
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
